### ISSUE TITLE
Less bright background!

### ISSUE THREAD

**Issue by CameronDiver** [product-os/jellyfish#3786] opened 2020-05-15 15:32 UTC
## Expected Behavior
A slightly less aggressive background brightness.

Obviously it's subjective but it feels extremely bright to be looking at super often.

## Actual Behavior
I have to wear sunglasses when using jellyfish :P

## Screenshots
actual screenshot of jellyfish: https://images.app.goo.gl/hL9snE9sSQwVXjTU7

## References

---

*Before submitting this issue, please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by LucianBuzzo** [comment] 2022-06-13 13:27
Draft PR here
Also duplicate of #2462

**Closed by LucianBuzzo** 2022-06-13 13:27 UTC
